/**
 * PM2 Ecosystem Configuration (TypeScript version)
 *
 * This configuration defines two environments:
 * - bouncer-dev: For development, with file watching enabled.
 * - bouncer-prod: For production, running in cluster mode.
 *
 * Both use the compiled output (dist/index.js) as the entry script.
 */

const config = {
  apps: [
    {
      name: 'bouncer-dev',
      // In development, we can watch for changes (and PM2 or a companion tool can be used for auto-restart)
      script: 'dist/index.js', // Ensure this file is generated by your build step (tsc)
      watch: true,
      ignore_watch: ['node_modules', 'logs'],
      env: {
        NODE_ENV: 'development',
        PORT: 8000,
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      max_memory_restart: '1G',
      merge_logs: true,
      log_rotate: true,
      max_size: '10M',
      retain: '30'
    },
    {
      name: 'bouncer-prod',
      script: 'dist/index.js',
      instances: 'max',
      exec_mode: 'cluster',
      watch: false,
      env: {
        NODE_ENV: 'production',
        PORT: 8000,
      },
      max_memory_restart: '1G',
      merge_logs: true,
      log_rotate: true,
      max_size: '10M',
      retain: '30'
    }
  ]
};

export = config; 